version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["/bin/ollama", "serve"]

volumes:
  ollama_data:
